# Generated by Django 5.1.3 on 2024-12-08 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoauthapi_app', '0002_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
